# Generated by Django 2.2.16 on 2021-08-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210816_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='mypassword', max_length=20),
        ),
    ]
