# Generated by Django 2.2.16 on 2021-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210816_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='mypassword', max_length=20, verbose_name='password'),
        ),
    ]
