# Generated by Django 2.2.16 on 2021-08-23 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория. model Category',
                'verbose_name_plural': 'Категории. model Category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания комментария')),
            ],
            options={
                'verbose_name': 'Комментарий. model Comment',
                'verbose_name_plural': 'Комментарии. model Comment',
                'ordering': ('review', 'author'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр. model Genre',
                'verbose_name_plural': 'Жанры. model Genre',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст отзыва')),
                ('score', models.SmallIntegerField(choices=[(1, '1. Очень плохо. Не понравилось совсем.'), (2, '2. Плохо. Не понравилось почти всё.'), (3, '3. Не очень. Не понравилось многое.'), (4, '4. Так себе. Мало что понравилось.'), (5, '5. Ни то, ни сё. Почти ничего не понравилось.'), (6, '6. Неплохо. Кое-что понравилось.'), (7, '7. Хорошо. Многое понравилось.'), (8, '8. Очень хорошо. Почти всё понравилось.'), (9, '9. Великолепно. Очень понравилось.'), (10, '10. Высший балл. В восторге.')], verbose_name='Оценка произведения пользователем')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв. model Review',
                'verbose_name_plural': 'Отзывы. model Review',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название произведения.')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год издания/публикации произведения.')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Category', verbose_name='Раздел портала.')),
                ('genre', models.ManyToManyField(related_name='genres', to='reviews.Genre')),
            ],
            options={
                'verbose_name': 'Произведение. model Title',
                'verbose_name_plural': 'Произведения. model Title',
                'ordering': ('category', 'name'),
            },
        ),
    ]
