# Generated by Django 2.2.16 on 2021-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(default='', max_length=300, verbose_name='Краткое представление произведения.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(related_name='titles', to='reviews.Genre'),
        ),
    ]
